services:
  db:
    container_name: buddy-db
    restart: always
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: buddy_db
      POSTGRES_PASSWORD: secure-password
      POSTGRES_USER: buddy-user

  adminer:
    container_name: buddy-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
