name: CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  serverQuality:
    name: Server quality
    runs-on: ubuntu-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v4

      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Bootstrap
        run: |
          just bootstrap-server

      - name: Run quality checks
        run: |
          just quality-server

  pushImage:
    name: Push image
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs:
      - serverQuality
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v4

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Build image
        run: |
          just build-server

      - name: Tag image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          just tag-server-image

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Push image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          just push-server-image
