name: Server CI

on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'

concurrency:
  group: ${{ github.ref }}-server
  cancel-in-progress: true

jobs:
  quality:
    name: Quality
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v4

      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Bootstrap
        run: |
          just bootstrap-server

      - name: Run quality checks
        run: |
          just quality-server

  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v4

      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Bootstrap
        run: |
          just bootstrap-server

      - name: Run tests
        run: |
          just test-server-cov
  
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v4
      
      - name: Install just
        uses: taiki-e/install-action@just

      - name: Build server
        run: |
          just build-server

      - name: Tag image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          just tag-server-image

  push:
    name: Push
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - quality
      - test
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v4

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Build image
        run: |
          just build-server

      - name: Tag image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          just tag-server-image

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Push image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          just push-server-image
